// Shader written by Enchanted_Games (https://enchanted.games)
// Please don't steal this code and use it without asking me first
// Any functions not made by me will include a credit line at the top of them

// Generated by https://outlines.enchanted.games

//    -- CONFIG STARTS HERE --
//         !! WARNING !!
//     Do not copy config from
//     an older version of this
//   pack, it will probably crash!

const vec4 block_COLOURS[] = vec4[](
	vec4(0.97647, 0.23922, 0.94902, 1),
	vec4(1, 1, 1, 0)
);
#define block_ANIM_SPEED 300
#define block_COLOUR_PERIOD 0.5
#define block_SMOOTH_MIX false
#define block_ANIMATE_WITH_DISTANCE true
#define block_ANIMATE_ALONG_LINES false
#define block_ANIM_DIRECTION 1
#define block_LINE_THICKNESS 1

const vec4 hitbox_COLOURS[] = vec4[](
	vec4(1, 0.4549, 0.06275, 1),
	vec4(0.99608, 0.88235, 0.07843, 1),
	vec4(1, 1, 1, 1)
);
#define hitbox_ANIM_SPEED 400
#define hitbox_COLOUR_PERIOD 0.5
#define hitbox_SMOOTH_MIX false
#define hitbox_ANIMATE_WITH_DISTANCE false
#define hitbox_ANIMATE_ALONG_LINES true
#define hitbox_ANIM_DIRECTION 1
#define hitbox_LINE_THICKNESS 2
#define hitbox_APPLY_TO_ALL_LINES false